ruban-discover:
    image: progrium/consul:latest
    container_name: ruban-discover
    hostname: ruban
    restart: always
    volumes:
        - ./data:/data
    ports:
        - "8300:8300"
        - "8301:8301"
        - "8301:8301/udp"
        - "8302:8302"
        - "8302:8302/udp"
        - "8400:8400"
        - "8500:8500"
        - "8600:53"
        - "53:53/udp"
    command: -server -bootstrap -ui-dir=/ui -advertise 192.168.50.84 -client 0.0.0.0
